---
apiVersion: v1
kind: Service
metadata:
  name: stunnel
  namespace: stunnel
  labels:
    app.kubernetes.io/name: stunnel
    app.kubernetes.io/component: tls-proxy
spec:
  type: ClusterIP
  ports:
    - name: tls
      protocol: TCP
      port: 6697
      targetPort: tls
  selector:
    app.kubernetes.io/name: stunnel
    app.kubernetes.io/component: tls-proxy
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
